Resources:
  MultitenantUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      UsernameAttributes: 
        - 'email'
      UserPoolName: 'multitenant-user-pool'
  MultitenantUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      ClientName: 'multitenant-user-pool-client'
      UserPoolId: !Ref MultitenantUserPool
      ExplicitAuthFlows: 
        - 'ADMIN_NO_SRP_AUTH'
      GenerateSecret: true
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: 
        - 'code'
        - 'implicit'
      AllowedOAuthScopes: 
        - 'openid'
        - 'profile'
        - 'email'
      SupportedIdentityProviders: 
        - 'COGNITO'
      CallbackURLs: 
        - 'https://example.com/callback'
      PreventUserExistenceErrors: 'ENABLED'
  PaymentUserPoolDomain: 
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: 'payment-example'
      UserPoolId: !Ref MultitenantUserPool
  ExampleUser:
    Type: AWS::Cognito::UserPoolUser
    Properties: 
      Username: 'nicolas.archila@pragma.com.co'
      UserPoolId: !Ref MultitenantUserPool
Outputs: 
    MultitenantUserPoolArn:
        Description: 'Export the MultitenantUserPoolArn'
        Value: !GetAtt MultitenantUserPool.Arn
        Export: 
            Name: MultitenantUserPoolArn  
    MultitenantUserPoolId:
        Description: 'Export the MultitenantUserPoolId'
        Value: MultitenantUserPool
        Export: 
            Name: MultitenantUserPoolId  

