Resources: 
    ApiCloudWatchRole: 
        Type: "AWS::IAM::Role"
        Properties: 
            AssumeRolePolicyDocument: 
                Version: "2012-10-17"
                Statement: 
                - 
                    Effect: "Allow"
                    Principal: 
                        Service: 
                            - "apigateway.amazonaws.com"
                            - "lambda.amazonaws.com"
                    Action: 
                        - "sts:AssumeRole"
    ApiCloudWatchPolicy:
        Type: 'AWS::IAM::Policy'
        DependsOn: 
            - ApiCloudWatchRole
        Properties:
            PolicyName: 'ApiCloudWatchPolicy'
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Action:
                        - 'logs:CreateLogGroup'
                        - 'logs:CreateLogStream'
                        - 'logs:DescribeLogGroups'
                        - 'logs:DescribeLogStreams'
                        - 'logs:PutLogEvents'
                        - 'logs:GetLogEvents'
                        - 'logs:FilterLogEvents'
                      Resource: '*'
            Roles: 
                - Ref: "ApiCloudWatchRole"
    AccountApi: 
        Type: AWS::ApiGateway::Account
        DependsOn: 
            - ApiCloudWatchPolicy
        Properties: 
            CloudWatchRoleArn: !GetAtt ApiCloudWatchRole.Arn
    PaymentRestApi:
        Type: AWS::ApiGateway::RestApi
        Properties:
            Body:
                swagger: 2
                info:
                    version: '0.0.1'
                    title: 'payment'
                basePath: '/payment'
                schemes: 
                    - 'https'
                definitions: 
                    Empty: 
                        type: 'object'
            Name: 'payment'
            Parameters: 
                endpointConfigurationTypes: 'REGIONAL'
    ProxyResource: 
        Type: AWS::ApiGateway::Resource
        Properties: 
            RestApiId: 
                !Ref PaymentRestApi
            ParentId: 
                !GetAtt 
                    - PaymentRestApi
                    - RootResourceId
            PathPart: 'payment'
    PaymentDeployment: 
        Type: AWS::ApiGateway::Deployment
        DependsOn: 
            - PaymentMethod
        Properties:
            RestApiId: 
                !Ref PaymentRestApi
            Description: 'My deployment'
    PaymentMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            ApiKeyRequired: true
            RestApiId: 
                !Ref PaymentRestApi
            ResourceId:
                !Ref ProxyResource
            HttpMethod: 'GET'
            AuthorizationType: 'COGNITO_USER_POOLS'
            AuthorizerId: !Ref PaymentAuthorizer
            Integration: 
                Type: 'AWS_PROXY'
                IntegrationHttpMethod: 'POST'
                Uri: 
                    !Sub
                        - 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function}/invocations'
                        - { Function: !ImportValue PaymentServiceArn }  
    PaymentServicePermission:
        Type: 'AWS::Lambda::Permission'
        Properties:
            FunctionName: !ImportValue PaymentService
            Action: lambda:InvokeFunction
            Principal: apigateway.amazonaws.com
            SourceAccount: !Ref 'AWS::AccountId'
            SourceArn: !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${PaymentRestApi}/*/*/*'
    PaymentAuthorizer:
        Type: 'AWS::ApiGateway::Authorizer'
        Properties:
            Type: COGNITO_USER_POOLS
            IdentitySource: method.request.header.Authorization
            Name: PaymentAuthorizer
            RestApiId: !Ref PaymentRestApi
            ProviderARNs: 
                - !ImportValue MultitenantUserPoolArn
Outputs: 
    PaymentRestApi:
        Description: 'Export the PaymentRestApi'
        Value: !Ref PaymentRestApi
        Export: 
            Name: PaymentRestApi  
    PaymentRestApiArn:
        Description: 'Export the PaymentRestApi'
        Value: !Join [":", ["arn", !Ref "AWS::Partition", "execute-api", !Ref "AWS::Region", !Ref "AWS::AccountId", !Ref PaymentRestApi]]
        Export: 
            Name: PaymentRestApiArn  
    ProxyResource:
        Description: 'Export the ProxyResource'
        Value: !Ref ProxyResource
        Export: 
            Name: ProxyResource 
    PaymentDeployment:
        Description: 'Export the PaymentDeployment'
        Value: !Ref PaymentDeployment
        Export: 
            Name: PaymentDeployment 
    
