Resources:
  PaymentSchedulerRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "scheduler.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  PaymentSchedulerPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'PaymentSchedulerPolicy'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'lambda:InvokeFunction'
            Resource:
              - !ImportValue PaymentServiceArn
      Roles: 
        - Ref: "PaymentSchedulerRole"
  PaymentScheduledTrigger:    
    Type: AWS::Scheduler::Schedule
    Properties: 
      Description: 'Event Bridge to trigger payment service'
      FlexibleTimeWindow: 
        Mode: 'OFF'
      Name: 'EventBridgeToTriggerPaymentService'
      ScheduleExpression: rate(1 minutes)
      State: 'ENABLED' 
      Target: 
        Arn: !ImportValue PaymentServiceArn
        RoleArn: !GetAtt PaymentSchedulerRole.Arn
